resolver: nightly-2020-11-19

packages:
- .

extra-deps:
- dir-traverse-0.2.2.3
- extensions-0.0.0.1
- microaeson-0.1.0.0
- trial-0.0.0.0
- trial-optparse-applicative-0.0.0.0
- trial-tomland-0.0.0.0
- unordered-containers-0.2.12.0
- numhask-0.7.0.0
- protolude-0.3.0
- random-1.2.0
- splitmix-0.1.0.3
- stan-0.0.1.0

allow-newer: true
